name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: codeobserver-poc/package-lock.json

      - name: Install dependencies
        working-directory: codeobserver-poc
        run: npm ci

      - name: Lint
        working-directory: codeobserver-poc
        run: npm run lint

      - name: Run tests
        working-directory: codeobserver-poc
        run: xvfb-run -a npm test

      - name: Package VSIX (smoke test)
        working-directory: codeobserver-poc
        run: |
          rm -f *.vsix
          npx vsce package --no-dependencies
