name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: codeobserver-poc/package-lock.json

      - name: Install dependencies
        working-directory: codeobserver-poc
        run: npm ci

      - name: Build VSIX
        id: build
        working-directory: codeobserver-poc
        shell: bash
        run: |
          set -euo pipefail
          npx rimraf *.vsix
          npx vsce package --no-dependencies
          VSIX_FILE=$(ls *.vsix)
          echo "vsix-file=$VSIX_FILE" >> "$GITHUB_OUTPUT"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Request OIDC token
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sigstore.dev');
            core.exportVariable('COSIGN_ID_TOKEN', token);

      - name: Sign VSIX (keyless)
        id: sign
        working-directory: codeobserver-poc
        shell: bash
        env:
          COSIGN_YES: "1"
          COSIGN_EXPERIMENTAL: "1"
        run: |
          set -euo pipefail
          VSIX_FILE="${{ steps.build.outputs.vsix-file }}"
          cosign sign-blob \
            --identity-token "$COSIGN_ID_TOKEN" \
            --output-signature "${VSIX_FILE}.sig" \
            --output-certificate "${VSIX_FILE}.pem" \
            "${VSIX_FILE}"
          echo "signature=${VSIX_FILE}.sig" >> "$GITHUB_OUTPUT"
          echo "certificate=${VSIX_FILE}.pem" >> "$GITHUB_OUTPUT"

      - name: Verify VSIX signature
        working-directory: codeobserver-poc
        shell: bash
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          set -euo pipefail
          cosign verify-blob \
            --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/release.yml@${{ github.ref }}" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --signature "${{ steps.sign.outputs.signature }}" \
            "${{ steps.build.outputs.vsix-file }}"

      - name: Upload VSIX to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: codeobserver-poc/${{ steps.build.outputs.vsix-file }}
          asset_name: ${{ steps.build.outputs.vsix-file }}
          asset_content_type: application/octet-stream

      - name: Upload signature to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: codeobserver-poc/${{ steps.sign.outputs.signature }}
          asset_name: ${{ steps.sign.outputs.signature }}
          asset_content_type: application/octet-stream

      - name: Upload certificate to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: codeobserver-poc/${{ steps.sign.outputs.certificate }}
          asset_name: ${{ steps.sign.outputs.certificate }}
          asset_content_type: application/x-pem-file
